dataset:
  name: sensebee
  dataset_dir: '/sensebee2/data/business_data/image_classification/5834'
  image_size: 224
  n_channels: 3
  n_classes: 2
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
